// return-data/src/components/Counter.tsx
import { type FC, useState } from "react";

interface Props {
  count: number;
  label?: string;
}

const Counter: FC<Props> = ({ count, label = "" }) => {
  console.log("Counter.tsx : count =", count);
  const [value, setValue] = useState(count);
  return (
    <div style={{ display: "flex", alignItems: "center", gap: "1rem" }}>
      {label && <div>{label}</div>}
      <button disabled={value <= 0} onClick={() => setValue((v) => v - 1)}>
        -
      </button>
      <div>{value}</div>
      <button onClick={() => setValue((v) => v + 1)}>+</button>
    </div>
  );
};

export default Counter;

// return-data/src/components/Counter.svelte
<script>
  export let count;
  export let label = "";
  console.log("Counter.svelte : count =", count);
</script>

<div class="row">
  {#if label}
    <div>{label}</div>
  {/if}
  <button disabled={count <= 0} on:click={() => count--}>-</button>
  <div>{count}</div>
  <button on:click={() => count++}>+</button>
</div>

<style>
  .row {
    display: flex;
    align-items: center;
    gap: 1rem;
  }
</style>
