// nanostores-demo/src/components/Counter.tsx
import {type FC, useState} from 'react';

interface Props {
  label?: string;
  start?: number;
}

const Counter: FC<Props> = ({label = '', start = 0}) => {
  const [count, setCount] = useState(start);

  return (
    <div style={{display: 'flex', alignItems: 'center', gap: '1rem'}}>
      {label && <div>{label}</div>}
      <button disabled={count <= 0} onClick={() => setCount(c => c - 1)}>
        -
      </button>
      <div>{count}</div>
      <button onClick={() => setCount(c => c + 1)}>+</button>
    </div>
  );
};

export default Counter;

// playground/src/components/Counter.svelte
<script>
  export let label = '';
  export let start = 0;

  let count = start;
</script>

<div class="row">
  {#if label}
    <div>{label}</div>
  {/if}
  <button disabled={count <= 0} on:click={() => count--}>-</button>
  <div>{count}</div>
  <button on:click={() => count++}>+</button>
</div>

<style>
  button, h1 {
    margin: 0;
  }

  .row {
    display: flex;
    align-items: center;
    gap: 1rem;
  }
</style>
